version: '3.9'
services:
  postgres:
    container_name: db
    network_mode: my-network
    environment:
      - POSTGRES_PASSWORD=foobarbaz
      - POSTGRES_DB=quick_recal_ai
    volumes:
      - 'pg_data_quick_recall_ai:/var/lib/postgresql/data'
    #   - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5432:5432'
    restart: always
    image: 'postgres:15.1-alpine'
volumes:
  pg_data_quick_recall_ai:
networks:
  my-network:
    driver: bridge